spring:
  application:
    name: Book Shop
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_shop
    username: root
    password: admin
